name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Store the executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: media-organizer
        path: target/debug/snowflake
        if-no-files-found: warn
        retention-days: 30
